[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sf_bc_one = "6Y7vUyZPsaK8MmgpxQ3aiFtxiai8ZVd3e55PFChp44Cy"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
